@startuml
actor Клиент as Client
participant Банкомат as ATM
participant Банк as Bank

Client ++
ATM ++
Client -> ATM: Вставить карту
Bank ++
ATM -> Bank: Проверить карту
alt #Pink Карта невалидна
Bank --> ATM: Карта невалидна
ATM --> Client: Выдать карту
end

Bank --> ATM: Карта валидна
Bank --
ATM --> Client: Запросить ПИН-код
Client -> ATM: Ввод ПИН-кода
Client --
loop Каждые 2 минуты,\nпока не будет ответа
ATM -> Bank: Проверить ПИН-код
Bank ++
end

alt #Pink Неверный ПИН-код
Bank --> ATM: Неверный ПИН-код
Bank --
ATM --> Client: Вывод сообщения\n"Неверный ПИН-код"
Client ++
else #Pink Исчерпан лимит попыток
ATM -> ATM: Блокировка карты
ATM --> Client: Вывод сообщения\n"Исчерпан лимит попыток.\nКарта заблокирована"
end

Client ->> ATM: Выбор функции "Снять"
Client -> ATM: Ввод суммы
Client --
ATM -> Bank: Проверить баланс
Bank ++

alt #Pink Недостаточно средств на счету
Bank --> ATM: Баланс меньше суммы
ATM --> Client: Вывод сообщения\n"Недостаточно средств"
Client ++
end

Bank --> ATM: Баланс равен или\nбольше суммы
Bank --
ATM --> Client: Выдать деньги

Client -> ATM: Запросить чек
ATM --> Client: Выдать чек
Client -> ATM: Запросить карту
ATM --> Client: Выдать карту
Client --
ATM --
@enduml
